
# compose para produção

services:
  app:
    image: ghcr.io/ggerake/projectmanager/app-prod:latest
    build:
      context: ../.. # vai para o diretório raiz do projeto
      dockerfile: docker/prod/Dockerfile
    container_name: app_project_manager_prod
    ports:
      - "9900:8000"
    command: >
      sh -c " ./docker/wait-for-it.sh db 5432 --
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000 &&
              gunicorn ProjectManager.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - USE_POSTGRES=1
      - POSTGRES_PORT=5432
  db:
    image: postgres:15-alpine
    container_name: db_project_manager_prod
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9932:5432"
    volumes:
      - db_project_manager_prod:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx_project_manager_prod
    ports:
      - "99:80"
    volumes:
      - ../../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db_project_manager_prod:
